# Generated by Django 4.2.1 on 2024-04-08 07:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название группового денежного сбора')),
                ('occasion', models.CharField(choices=[('birthday', 'День рождения'), ('wedding', 'Свадьба'), ('charity', 'Благотворительность')], default='birthday', max_length=2000, verbose_name='Повод группового денежного сбора')),
                ('description', models.CharField(max_length=2000, verbose_name='Описание группового денежного сбора')),
                ('aim_sum', models.IntegerField(default=0, verbose_name='Цель группового денежного сбора, р')),
                ('infinity_sum', models.BooleanField(default=False, verbose_name='Флаг бесконечного сбора')),
                ('current_sum', models.IntegerField(default=0, verbose_name='Собранная сумма в данный момент, р')),
                ('number_of_people', models.IntegerField(default=0, verbose_name='Количество людей, участвующих в групповом денежном сборе')),
                ('collect_cover', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Обложка группового денежного сбора')),
                ('finish_collect_date_time', models.DateTimeField(default=datetime.datetime(2024, 4, 8, 7, 45, 42, 680090, tzinfo=datetime.timezone.utc), verbose_name='Дата завершения сбора')),
                ('collect_lent', models.TextField(default='', verbose_name='Лента сбора')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор группового денежного сбора')),
            ],
            options={
                'verbose_name': 'Групповой денежный сбор',
                'verbose_name_plural': 'Групповые денежные сборы',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.IntegerField(verbose_name='Сумма платежа, р')),
                ('collect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_api.collect', verbose_name='Групповой денежный сбор')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь донатер')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
            },
        ),
    ]
